/**
 * GitHub App認証
 *
 * GitHub App設定があれば gh/git ラッパースクリプトを自動生成し、
 * エージェントの PATH 先頭に差し込む。GitHub 操作時にtool-server経由でトークンを取得。
 *
 * 秘密鍵は起動時にメモリに読み込み、ファイルシステムには残さない。
 * トークン生成はtool-serverのHTTPエンドポイント経由で行い、
 * 子プロセス（Claude Code等）から秘密鍵にアクセスできないようにする。
 */
import { writeFileSync, mkdirSync, chmodSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';

interface GitHubAppConfig {
  appId: string;
  installationId: string;
  /** メモリ上に保持した秘密鍵の内容 */
  privateKey: string;
}

let appConfig: GitHubAppConfig | null = null;

// ラッパースクリプトの配置先
const WRAPPER_DIR = '/tmp/xangi-gh-wrapper';
const GH_WRAPPER_PATH = join(WRAPPER_DIR, 'gh');
const GIT_WRAPPER_PATH = join(WRAPPER_DIR, 'git');
const GIT_CREDENTIAL_HELPER_PATH = join(WRAPPER_DIR, 'git-credential-helper');
const WRAPPER_ENV_PATH = join(WRAPPER_DIR, 'env.sh');

/**
 * GitHub App設定を初期化しラッパーを生成
 *
 * 秘密鍵をファイルから読み込んでメモリに保持する。
 * ファイル自体は読み込み後にアクセス不要。
 */
export function initGitHubAuth(): void {
  const appId = process.env.GITHUB_APP_ID;
  const installationId = process.env.GITHUB_APP_INSTALLATION_ID;
  const privateKeyPath = process.env.GITHUB_APP_PRIVATE_KEY_PATH;

  if (appId && installationId && privateKeyPath) {
    // Docker環境ではマウント先の固定パスを使用
    const dockerPemPath = '/secrets/github-app.pem';
    const resolvedKeyPath = existsSync(dockerPemPath) ? dockerPemPath : privateKeyPath;

    // 秘密鍵をメモリに読み込み
    let privateKey: string;
    try {
      privateKey = readFileSync(resolvedKeyPath, 'utf-8');
    } catch (err) {
      console.error(`[github-auth] Failed to read private key from ${resolvedKeyPath}:`, err);
      console.log('[github-auth] Falling back to default gh authentication');
      return;
    }

    appConfig = { appId, installationId, privateKey };
    generateWrapper();
    console.log(`[github-auth] GitHub App mode enabled (App ID: ${appId})`);
  } else {
    console.log('[github-auth] Using default gh authentication');
  }
}

/**
 * GitHub App が有効かどうか
 */
export function isGitHubAppEnabled(): boolean {
  return appConfig !== null;
}

/**
 * エージェントの PATH に追加すべきディレクトリ
 * App モード: ラッパーディレクトリを返す
 * 通常モード: undefined
 */
export function getGitHubWrapperDir(): string | undefined {
  return appConfig ? WRAPPER_DIR : undefined;
}

/**
 * PATH にラッパーディレクトリを先頭固定する。
 *
 * 子プロセスの login shell や rc file が PATH を再構築しても、重複した
 * ラッパーディレクトリを取り除いた上で先頭に戻せるようにする。
 */
export function withGitHubWrapperPath(pathValue: string | undefined): string {
  const parts = (pathValue || process.env.PATH || '')
    .split(':')
    .filter((part) => part && part !== WRAPPER_DIR);
  return [WRAPPER_DIR, ...parts].join(':');
}

/**
 * エージェントプロセスに渡す環境変数を取得
 * App モード: PATH にラッパーディレクトリを先頭固定し、bash 起動時にも再適用
 * 通常モード: 空オブジェクト
 */
export function getGitHubEnv(
  baseEnv: NodeJS.ProcessEnv | Record<string, string>
): Record<string, string> {
  if (!appConfig) return {};
  const currentPath = baseEnv['PATH'] || process.env.PATH || '';
  return {
    PATH: withGitHubWrapperPath(currentPath),
    BASH_ENV: WRAPPER_ENV_PATH,
  };
}

/**
 * GitHub App Installation Tokenを生成
 *
 * tool-serverから呼ばれる。メモリ上の秘密鍵を使って
 * 短寿命（1時間）のInstallation Tokenを生成する。
 */
export async function generateInstallationToken(): Promise<string> {
  if (!appConfig) {
    throw new Error('GitHub App is not configured');
  }

  // 動的import（パッケージがインストールされていない環境でもビルドが通るように）
  const { createAppAuth } = (await import('@octokit/auth-app' as string)) as {
    createAppAuth: (...args: unknown[]) => { (opts: { type: string }): Promise<{ token: string }> };
  };

  const auth = createAppAuth({
    appId: appConfig.appId,
    privateKey: appConfig.privateKey,
    installationId: parseInt(appConfig.installationId, 10),
  });

  const { token } = await auth({ type: 'installation' });
  return token;
}

/**
 * gh/gitラッパースクリプトを生成
 *
 * tool-serverのHTTPエンドポイント経由でトークンを取得するラッパー。
 * 秘密鍵へのアクセスは不要。
 */
function generateWrapper(): void {
  mkdirSync(WRAPPER_DIR, { recursive: true });

  const envHook = `# Generated by xangi. Re-assert GitHub App gh wrapper precedence.
_xangi_gh_wrapper_dir="${WRAPPER_DIR}"
_xangi_path_without_wrapper=""
_xangi_old_ifs="$IFS"
IFS=:
for _xangi_path_entry in $PATH; do
  if [ "$_xangi_path_entry" = "$_xangi_gh_wrapper_dir" ] || [ -z "$_xangi_path_entry" ]; then
    continue
  fi
  if [ -z "$_xangi_path_without_wrapper" ]; then
    _xangi_path_without_wrapper="$_xangi_path_entry"
  else
    _xangi_path_without_wrapper="$_xangi_path_without_wrapper:$_xangi_path_entry"
  fi
done
IFS="$_xangi_old_ifs"
export PATH="$_xangi_gh_wrapper_dir\${_xangi_path_without_wrapper:+:$_xangi_path_without_wrapper}"
unset _xangi_gh_wrapper_dir _xangi_path_without_wrapper _xangi_old_ifs _xangi_path_entry
`;
  writeFileSync(WRAPPER_ENV_PATH, envHook, 'utf-8');
  chmodSync(WRAPPER_ENV_PATH, 0o755);

  // gh ラッパーシェルスクリプト
  // XANGI_TOOL_SERVER経由でトークンを取得（秘密鍵不要）
  const wrapper = `#!/bin/bash
if [ -z "$XANGI_TOOL_SERVER" ]; then
  echo "Error: XANGI_TOOL_SERVER is not set" >&2
  exit 1
fi
export GH_TOKEN="$(curl -sf "$XANGI_TOOL_SERVER/github-token")"
if [ -z "$GH_TOKEN" ]; then
  echo "Error: Failed to get GitHub App token from tool-server" >&2
  exit 1
fi
real_gh=""
_xangi_old_ifs="$IFS"
IFS=:
for _xangi_path_entry in $PATH; do
  [ -z "$_xangi_path_entry" ] && continue
  _xangi_candidate="$_xangi_path_entry/gh"
  if [ "$_xangi_candidate" = "${GH_WRAPPER_PATH}" ]; then
    continue
  fi
  if [ -x "$_xangi_candidate" ]; then
    real_gh="$_xangi_candidate"
    break
  fi
done
IFS="$_xangi_old_ifs"
unset _xangi_old_ifs _xangi_path_entry _xangi_candidate
if [ -z "$real_gh" ]; then
  echo "Error: real gh command not found" >&2
  exit 1
fi
exec "$real_gh" "$@"
`;
  writeFileSync(GH_WRAPPER_PATH, wrapper, 'utf-8');
  chmodSync(GH_WRAPPER_PATH, 0o755);

  // git credential helper
  // GitHub HTTPS の credential 要求時だけ installation token を返す。
  const gitCredentialHelper = `#!/bin/bash
set -euo pipefail

if [ "\${1:-}" != "get" ]; then
  exit 0
fi

protocol=""
host=""
while IFS= read -r line; do
  [ -z "$line" ] && break
  case "$line" in
    protocol=*) protocol="\${line#protocol=}" ;;
    host=*) host="\${line#host=}" ;;
  esac
done

if [ "$protocol" != "https" ] || [ "$host" != "github.com" ]; then
  exit 0
fi

if [ -z "\${XANGI_TOOL_SERVER:-}" ]; then
  echo "Error: XANGI_TOOL_SERVER is not set" >&2
  exit 1
fi

token="$(curl -sf "$XANGI_TOOL_SERVER/github-token")"
if [ -z "$token" ]; then
  echo "Error: Failed to get GitHub App token from tool-server" >&2
  exit 1
fi

printf 'username=x-access-token\\n'
printf 'password=%s\\n' "$token"
`;
  writeFileSync(GIT_CREDENTIAL_HELPER_PATH, gitCredentialHelper, 'utf-8');
  chmodSync(GIT_CREDENTIAL_HELPER_PATH, 0o755);

  // git ラッパーシェルスクリプト
  // 既存の gh credential helper を bypass し、GitHub HTTPS は App token helper に寄せる。
  const gitWrapper = `#!/bin/bash
set -euo pipefail

real_git=""
_xangi_old_ifs="$IFS"
IFS=:
for _xangi_path_entry in $PATH; do
  [ -z "$_xangi_path_entry" ] && continue
  _xangi_candidate="$_xangi_path_entry/git"
  if [ "$_xangi_candidate" = "${GIT_WRAPPER_PATH}" ]; then
    continue
  fi
  if [ -x "$_xangi_candidate" ]; then
    real_git="$_xangi_candidate"
    break
  fi
done
IFS="$_xangi_old_ifs"
unset _xangi_old_ifs _xangi_path_entry _xangi_candidate
if [ -z "$real_git" ]; then
  echo "Error: real git command not found" >&2
  exit 1
fi

export GIT_TERMINAL_PROMPT=0
exec "$real_git" \\
  -c credential.helper= \\
  -c "credential.https://github.com.helper=!${GIT_CREDENTIAL_HELPER_PATH}" \\
  "$@"
`;
  writeFileSync(GIT_WRAPPER_PATH, gitWrapper, 'utf-8');
  chmodSync(GIT_WRAPPER_PATH, 0o755);
}
